services:
  smtp4dev-message-sender:
    image: rnwood/smtp4dev
    ports:
      - 3000:80
    expose:
      - 25
  redis-message-sender:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis-message-sender-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  message-sender-api:
    build: .
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      redis-message-sender:
        condition: service_healthy

volumes:
  redis-message-sender-data:
